adding files to the repository
Danelif/portfoliofull pull request #1
Opened 2022-06-30 16:13 UTC by Danelif

2022-06-30 16:53 UTC, chrystalme requested changes
## Hi @Danelif , 

You have done a good job so far!
However, there are some issues that you still need to work on to prepare your project for further evaluation
## Highlights 💡 
✔️ Linters well configured and passing all tests
✔️ HTML code looks mostly semantically correct.
## Suggested changes ♻️ 
_Check the comments under the review._
Also, you need to work on your design. 
|Figma Design| Your Design|
|---|---|
|![image](https://user-images.githubusercontent.com/12239821/176733160-cbc4d5f8-d1f7-4467-8cd3-60d17e647620.png)|![image](https://user-images.githubusercontent.com/12239821/176733186-16ff6a3f-1bb1-4148-aff9-774a7b2d4cb1.png)|

- I have made annotations where I see disparity with your design.
- You have made just 2 commits in this entire project and this is not acceptable. You have to make frequent commits or it seems as if you are copying the code and pasting. Kindly make frequent commit at every stage of the development process.

## Optional Changes
This project is intended to be designed using the mobile first approach. You have not followed this approach and I think it would be a problem for you trying to design for the other screens.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Also, you can reach me on [Twitter](https://twitter.com/afam_ifeanyi) or [Slack](https://microverse-community.slack.com/team/U019ZC99KFA). Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 16:53 UTC, chrystalme commented on index.html
> +              <div class="project-buttons">
Your text size here seems too large compared to design. Kindly use an alternative header like `<h3>`

2022-06-30 16:53 UTC, chrystalme commented on README.md
> +
Kindly customise the handles of your social and professional networks. Use the [microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md).

2022-06-30 20:31 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @Danelif. ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Good feature branch name ✔️ 
- Good commit messages  ✔️
- Professional Pull request and description ✔️
- Good UI ✔️
- Linters are passing ✔️ 
- Good use of semantic tags ✔️

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread `1GORDON` if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-30 20:31 UTC, 1GORDON commented on README.md
> +
Hello @Danelif.👏

- [ ] [Optional] Like the previous reviewer pointed out. Please customize your readme accordingly. You may use this [readme](https://github.com/microverseinc/readme-template/blob/master/README.md) template for guidance.

2022-06-30 20:31 UTC, 1GORDON commented on index.html
> +      </div>
Great job @Danelif. 👏

- [ ] [Optional] Please try your best to follow the Figma design.
- Your design
![works yours](https://user-images.githubusercontent.com/63917725/176770811-bb7aed22-0410-48fe-a259-a535c6132b24.PNG)

- Figma design
![works](https://user-images.githubusercontent.com/63917725/176770858-2d4889b1-2eea-4213-af4a-8733f1ab5d6f.PNG)

2022-06-30 20:31 UTC, 1GORDON commented on index.html
> +      <span> <img src="images/burger.png" alt="toggle icon" /> </span>
Nice work @Danelif ✔️

- [ ] [Optional] please try to surround your hamburger icon with an`<a>` tag. This is because this icon is also clickable

2022-07-01 04:34 UTC, Danelif commented
Thank you

2022-07-01 04:34 UTC, merged